### ISSUE TITLE
NoneType is not iterable - if user albums or favorites etc. are empty

### ISSUE THREAD

**Issue by HolyMess** [bloha/rajce-dl#1]
First of all, never seen such a ton of code which looks 'very academic'!
Especially the possibility to retrieve content via archive.org is amazing.

Anyway, I found reproducible bug(s).

If the user has no albums online, or has no favorite albums, the app will raise an exception NoneType is not iterable, which also breaks the search on the archive.

By the way, for specific albums it will hang at the download, even not trying to download the first object, as can be seen in the folder, but I have to reproduce that issue.

Further ideas:
- do not re-download content again, if user/album (and files?) are already on disk ~
- isn't chunk_size 1024 too small, maybe increase? ~
- max_workers is not set, so it will use count of cpus multiplied with 5 ~
- progress information could be improved, you often don't know what the app is doing currently (e.g. if trying the archive)
- starting the gui could be simplified, plus the gui hangs often while working, but there is at least progress output in the console

~ : this could be configurable

**Comment by HolyMess** [comment]
Hi and wow, thanks! I didn't check it out yet, but will soon do. Seems you fixed the NoneType thing in master, and improved progress in dev branch. But as said, didn't try it yet.

Next could be to prevent re-downloading stuff. That could be an easy check when creating the folder on disk: is the folder already existing, and has it the amount of files in it, then skip it with a progress message? Another idea to improve progress messages is to display also the user, so: user/album.. 35% [### ... ] - unless there is a reason why you don't like to use the full 80 columns or more in the console ;-)

**Comment by HolyMess** [comment]
I also pimped these things:

setup.py: added wheel, but don't know if it's really required, in my case it was complaining
`
    install_requires=[
        'wheel',
        'requests'
    ],
`

README.md: added
`
Default for --format is:

    '%(album_owner)/%(album_name_on_server)/%(file_name_on_server)'
`

To prevent re-download I added those lines, but without checking if files in folder:

album_downloader.py:
```
    def download(self):
        if self.__album:
            if album_files := self.__album.files:
                if self.__create_download_directory():
```

```
    def __create_download_directory(self):
        path = self.__path_formatter.download_folder
        if path:
            if os.path.exists(path):
                print(f'{path} skipped, exists already.')
                return False
            os.makedirs(path, exist_ok=True)
            return True
```

**Comment by HolyMess** [comment]
So the NoneType bug seems to be gone, BUT: it seems if a user has no albums online, it will even not try the archive, although in one case there were albums in archive.

**Comment by bloha** [comment]
> So the NoneType bug seems to be gone, BUT: it seems if a user has no albums online, it will even not try the archive, although in one case there were albums in archive.

Such functionality is not implemented yet.

**Comment by HolyMess** [comment]
Okay, I thought it would check for any albums of the user on the archive. Now I guess it will only try those albums which are e.g. not shown online (but still in the JSON?) or protected now. Is my assumption correct? As you can see it's not really clear for me, how this archive thing works. Anyway, thanks for your great work!

**Comment by bloha** [comment]
Yes, currently, it downloads only albums that are present in the JSON.

**Comment by bloha** [comment]
Just to make it more clear:
We take only metadata from the archive.
We do not download archived thumbnails, but we use metadata to retrieve real images and videos from the rajce servers. All "protected" albums are still public.
So if an album was deleted from the servers (not present in the JSON), there is no way to get it (only thumbnails, but it is not implemented).

**Comment by bloha** [comment]
>     * max_workers is not set, so it will use count of cpus multiplied with 5 ~
Since python 3.8 default value for max_workers is min(32, os.cpu_count() + 4)

**Comment by HolyMess** [comment]
Thanks for all the effort and a big WOW about how the archive is used. I guess this involves the "server range check" I stumbled over days ago. The only thing still missing is to prevent unnecessary re-downloads, if album and files are already on disk, but I just re-integrated my code changes from above to do so.

**Comment by HolyMess** [comment]
Again, good work! We could also close this issue, as most of the things have been resolved (except the "re-download prevention", which could classify as another issue/enhancement).

**Comment by bloha** [comment]
599d638b8068b619bb8a9a6ccb07544cd053343e That's what I call a "temporary solution". :smile:  
Checksums are not supported.
This code should be replaced with journaling in the future.

**Comment by HolyMess** [comment]
I switched to dev and tested it, using https://test.rajce.idnes.cz/Presazeni_rajcete/

1. First download, all okay.
2. Second download, it skips, perfect.
3. If deleting the last two images Obraz028 & Obraz029 and then re-downloading it will download the missing files, but maybe we could change the progress bar, currently this:
Presazeni_rajcet...           (2/11)  [####------------------]   18%
to:
test/Presazeni_rajcet...           (2/2)  [######################]   100%

But this is just UI stuff, it was first confusing, but I understand now how it happened, and maybe this was also meant to be the temporary solution. Functionality is perfect!

**Comment by bloha** [comment]
>     * starting the gui could be simplified, plus the gui hangs often while working, but there is at least progress output in the console

I will rewrite the GUI from scratch. It will be based on a web browser (local server + client).
So I mark this issue as closed.
