### ISSUE TITLE
If an album ends with "...", the downloader hangs

### ISSUE THREAD

**Issue by HolyMess** [bloha/rajce-dl#3]
If you try to retrieve an album which ends with a lot of dots (like "name..."), it seems that the user and album folder is created without the dots, but the downloader will hang forever, not even downloading the first file. Reproduction e.g. with: 
andiee.rajce.idnes.cz/10.6.2011%2C_.../

I am just guessing it's about the special chars (.:? etc), 
which are maybe even different per OS. Unfortunately only found them for Windows yet:

https://en.wikipedia.org/wiki/Filename#Reserved_characters_and_words

**Comment by bloha** [comment]
> I am just guessing it's about the special chars (.:? etc)
Yes, formatters %(file_name_on_server) and %(album_name_on_server) are only UNIX-safe.
I will add different ones for Windows.
Currently, you can use %(album_id_on_server) and %(file_id_on_server).

**Comment by bloha** [comment]
Real filenames are in use now (the code was in the software, but had no use).
So Unicode characters and original video names are now present.

**Comment by HolyMess** [comment]
I used latest dev branch, but the bug is still not going away. It hangs forever with 0% progress bar. I see you create now folder with _ for spaces.

Furthermore, after it created the user and album folder and don't downloaded anything, the next time you  re-start the app and try the same url again it it will throw another exception:

  File "..\rajce-dl\rajce_dl\album\downloader\local_directory_manager.py", line 69, in __calculate_directory_size
    return len(os.listdir(self.__path_formatter.download_folder))

FileNotFoundError: [WinError 3]

I could help debugging it with Pycharm, if I would know how to set it up to do so. If I try to run command.py I get:

Traceback (most recent call last):
  File "../rajce-dl/rajce_dl/command.py", line 12, in <module>
    from .location.rajce_location_factory import RajceLocationFactory
ImportError: attempted relative import with no known parent package

Do I need to workaround this maybe with some kind of "extending the path"?

**Comment by HolyMess** [comment]
Okay, meanwhile I managed it how to setup for debug, will  have a deeper look what happens here soon.

**Comment by HolyMess** [comment]
Okay, I see that

mkdir(name, mode)

in makedirs.py of os.py is still executed on Windows with:
'andiee/10.6.2011 ...'

which is illegal (for the 3 dots, and maybe the space)

Who is the culprit? If I go through track stace this is executed by local_directory_manager.py, line 18 (on dev):

    def create_download_directory(self):
        os.makedirs(self.__path_formatter.download_folder, exist_ok=True)

But I have not found about the other bug (if it failed and you re-try to download it will immediately throw an exception) yet.

**Comment by bloha** [comment]
Even if you find the cause of the problem, there is currently another error causing data loss (if some albums have the same names after character whitelisting). :sweat_smile: 
Now I remember why I disabled real names since version 1.1.1.
I will try to refactor the downloader. It is too ugly.

The web GUI is not abandoned. I'm just disappointed in Flask. It hides too much and has limitations.

**Comment by HolyMess** [comment]
I liked Flask because it felt easy for me to setup and use. Entrypoints for URLs, a little bit templating, sending and receiving parameters. But I am no expert in it.

**Comment by bloha** [comment]
> which is illegal (for the 3 dots, and maybe the space)

But NTFS should support dots in the names.

Try to change _CHARACTERS_WHITE_LIST to `r'[^\w\s\-\(\)]'`

**Comment by HolyMess** [comment]
I did as wished, but it still hangs. The folder itself is named then "1062011". I guess single dots are allowed (as it's no problem to create a folder "10.6.2011"), but dots in the end are illegal, because it could be a file ending.

The local_directory_manager tries to create the makedir then with:
'andiee/1062011 '

so we might have to trim it additonally?

**Comment by bloha** [comment]
try `r'[^\w\-\(\)]'`

**Comment by HolyMess** [comment]
So that leads also to the other bug: the next time you re-try to download the album by restarting the app it tells you it could not find the folder (see last space):
'andiee/1062011 '

Because it's in fact created, but as:
'andiee/1062011'

If you do mkdirs with Py on Windows with "name " it will create "name", returning no errors as far as I know.

**Comment by HolyMess** [comment]
Okay, if also removing space from allowed characters it's working and so could download all the files. But IMHO space (except of the end) and single dots can be allowed, just not:
- space(s) at the end (=> trim / strip)
- or dots at the end (maybe search \.+$ and replace?)

**Comment by HolyMess** [comment]
I just tried in Windows explorer what happens in reality:

"1.2.3.4.5" => "1.2.3.4.5"
"abc.." => "abc"
"abc." => "abc"
"..abc" => "..abc"
" spaces " => "spaces"

So we see spaces are trimmed at begin and end, and dots ONLY at the end.

**Comment by bloha** [comment]
> So we see spaces are trimmed at begin and end, and dots ONLY at the end.

Dots at the beginning mean that a file is hidden (on UNIX), so it is better to remove them.

**Comment by HolyMess** [comment]
I reverted changes and then re-pulled dev branch but now the folder created is:
andiee/4985439 and the files inside are 363014344, 363014345 etc. with no file ending, uh, or should it be like that? Then I prefer the former variant, even if not working for "..." ;-)

**Comment by HolyMess** [comment]
Great! That worked. However we might be a little bit too conservative now, because the folder misses the ",_" which both are legal in Windows and I guess also for Unix-like OS. I just try to prove it for Windows, yep, no problem:

"10.6.2011,_" => "10.6.2011,_"

",_name_," => ",_name_,"

**Comment by HolyMess** [comment]
Bug 2 is also solved now, it finds the old folder when re-starting and re-downloading.

**Comment by bloha** [comment]
> ",_"

But _ should be covered with \w

**Comment by HolyMess** [comment]
Yep, on Windows it's gone.. using my debugger I see it calls mkdirs with
'andiee/10.6.2011'

**Comment by bloha** [comment]
> 'andiee/10.6.2011'

var albumName = "10.6.2011, ...";
This is the original name, it does not contain any underscores.

Progress line shows %(album_name_on_sever).
Rajce server converts spaces to underscores.

**Comment by HolyMess** [comment]
Ah, okay, you're right, of course. The underscore was just in my head and is in fact a space, which would be illegal at start or end. So we have to fight about "," now ;-)

**Comment by bloha** [comment]
What about ~ ! @ [ ] and other chars?

**Comment by HolyMess** [comment]
To be honest, I would use a blacklist instead of a whitelist, using the Wikipedia article. But let's try for Windows, all of them are okay:

"~!@[]" => "~!@[]"

Totally illegal are: 

`\ / : * ? " < > |`

**Comment by HolyMess** [comment]
Is it Christmas or wish-driven development? Very fine. It now creates:
'andiee/10.6.2011,'

Checked against bug 1 and 2, both is working now. I might close the issue.
